# Generated by Django 5.2.8 on 2025-11-20 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_no', models.CharField(max_length=20, unique=True, verbose_name='챠트번호')),
                ('name', models.CharField(max_length=50, verbose_name='성명')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, null=True, verbose_name='성별')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='연락처')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='주소')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='내원일시')),
                ('chief_complaint', models.CharField(blank=True, max_length=200, null=True, verbose_name='주호소')),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True, verbose_name='진단명')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='chart.patient')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100, verbose_name='약품명')),
                ('dose', models.CharField(blank=True, max_length=50, null=True, verbose_name='1회량')),
                ('frequency', models.CharField(blank=True, max_length=50, null=True, verbose_name='횟수')),
                ('days', models.IntegerField(blank=True, null=True, verbose_name='일수')),
                ('instruction', models.CharField(blank=True, max_length=200, null=True, verbose_name='복약법')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='chart.visit')),
            ],
        ),
    ]
