# Generated by Django 5.2.8 on 2025-11-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_documentcategory_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/help_images/')),
                ('attach_file', models.FileField(blank=True, null=True, upload_to='uploads/help_docs/')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
